POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 25000,
  "make": "Toyota",
  "model": "Camry",
  "year": 2020,
  "mileage": 50000,
  "lng": -118.2437,
  "lat": 34.0522
}

################################################################################

GET http://localhost:3000/reports?make=Toyota&model=Camry&lng=-118.2437&lat=34.0522&mileage=50000&year=2020
Content-Type: application/json

################################################################################


GET  http://localhost:3000/reports
Content-Type: application/json

################################################################################

GET  http://localhost:3000/reports/1
Content-Type: application/json

################################################################################

PATCH    http://localhost:3000/reports/5/approve
Content-Type: application/json

{
  "approved": true
}

################################################################################

DELETE http://localhost:3000/reports/6
Content-Type: application/json